backend:
  name: git-gateway
  repo: theredwillow/chili-when-its-chilly
  branch: relation-widget # IMPORTANT Set this back to master before deploy
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

local_backend: true

media_folder: static/img
public_folder: /img

collections:
  - name: "required-page"
    label: "Required Pages"
    label_singular: "Required Page"
    files:
      - file: "src/pages/index.md"
        label: "Home Page"
        name: "index"
        fields:
          - label: "Template Key"
            name: "templateKey"
            widget: "hidden"
            default: "page" # Uses same template as pages collection, no way to create non-optional list item.
          - label: "Title"
            name: "title"
            widget: "hidden"
            default: "Home Page"
          - label: "Description"
            name: "description"
            widget: "text"
            hint: "Please provide a description of what is on this page so that search engines can display what to expect on your page more accurately."
          - name: "slideshowImages"
            label: "Slideshow Image" 
            widget: "list"
            required: false
            summary: '{{fields.description}}'
            hint: "Optional. Choose images to add a slideshow at the top of the page."
            fields:
              - label: "Image"
                name: "src"
                widget: "image"
                media_folder: "/{{media_folder}}/slideshow"
                public_folder: "/{{public_folder}}/slideshow"
              - label: "Description"
                name: "description"
                widget: "string"
                hint: "Please provide a description of what's in this image so that blind people can enjoy it too."
          - label: "Sections"
            name: "sections"
            widget: "list"
            field: {label: "Section", name: "section", widget: "markdown"}
          - name: "sponsorImages"
            label: "Sponsor Image" 
            widget: "list"
            required: false
            summary: '{{fields.description}}'
            fields:
              - label: "Image"
                name: "src"
                widget: "image"
                media_folder: "/{{media_folder}}/sponsors"
                public_folder: "/{{public_folder}}/sponsors"
              - label: "Description"
                name: "description"
                widget: "string"
                hint: "Please provide a description of what's in this image so that blind people can enjoy it too."
              - label: "Web Site"
                name: "url"
                widget: "string"
                hint: "Please use https, not http whenever possible."
          - label: "Contact Us copy"
            name: "contactCopy"
            widget: "markdown"
          - name: "externalLinks"
            label: "External Links"
            widget: "list"
            summary: '{{fields.title}}'
            fields:
              - label: "Title"
                name: "title"
                widget: "string"
              - label: "URL"
                name: "url"
                widget: "string"
                hint: "Please use https, not http whenever possible."
              - label: "Description"
                name: "description"
                widget: "text"
                hint: "Please provide a description of what is on this page so that users will know what to expect when they click the link."
      - file: "src/pages/cook-offs/index.md"
        label: "Cook Off's"
        name: "cook-offs-page"
        fields:
          - label: "Template Key"
            name: "templateKey"
            widget: "hidden"
            default: "cook-offs-page"
          - label: "Title"
            name: "title"
            widget: "hidden"
            default: "Cook Off's"
          - label: "Description"
            name: "description"
            widget: "text"
            hint: "Please provide a description of what is on this page so that search engines can display what to expect on your page more accurately."
          - {label: "Rules", name: "rules", widget: "markdown"}
  - name: "cook-off"
    label: "Cook Off's"
    label_singular: "Cook Off"
    folder: src/pages/cook-offs
    path: '{{slug}}/index'
    create: true
    fields:
      - label: "Template Key"
        name: "templateKey"
        widget: "hidden"
        default: "cook-off"
      - label: "Contest Name"
        name: "title"
        widget: "string"
        hint: "Avoid using the definite article (i.e. 'The'). This is taken care of by the code when necessary."
      - label: "Image"
        name: "image"
        widget: "image"
        hint: "The logo/image for this year's competition."
        media_folder: ""
      - name: "prevYears"
        label: "Previous Years"
        widget: "list"
        summary: "{{fields.year}}"
        required: false
        hint: "Provide previous years' images and names for the winners' gallery."
        fields:
          - label: "Year"
            name: "year"
            widget: "string"
            pattern: ['^\d{4}$', "Must be a four-digit year (i.e. 2000)."]
          - label: "Winners"
            name: "winners"
            widget: "object"
            required: false
            fields:
              - label: "First Place"
                name: "firstPlace"
                widget: "object"
                summary: "1st: {{fields.winnersName}}"
                required: false
                fields:
                  - label: "Winner's Name"
                    name: "winnersName"
                    widget: "string"
                    required: false
                  - label: "Winner's Picture"
                    name: "winnersPicture"
                    widget: "image"
                    media_folder: "winners"
                    public_folder: "/{{public_folder}}/winners"
                    hint: "Picture of 1st place winner, preferably holding trophy or entry."
              - label: "Second Place"
                name: "secondPlace"
                widget: "object"
                summary: "2nd: {{fields.winnersName}}"
                required: false
                fields:
                  - label: "Winner's Name"
                    name: "winnersName"
                    widget: "string"
                    required: false
                  - label: "Winner's Picture"
                    name: "winnersPicture"
                    widget: "image"
                    media_folder: "winners"
                    public_folder: "/{{public_folder}}/winners"
                    hint: "Picture of 2nd place winner, preferably holding trophy or entry."
              - label: "Third Place"
                name: "thirdPlace"
                widget: "object"
                summary: "3rd: {{fields.winnersName}}"
                required: false
                fields:
                  - label: "Winner's Name"
                    name: "winnersName"
                    widget: "string"
                    required: false
                  - label: "Winner's Picture"
                    name: "winnersPicture"
                    widget: "image"
                    media_folder: "winners"
                    public_folder: "/{{public_folder}}/winners"
                    hint: "Picture of 3rd place winner, preferably holding trophy or entry."
  - name: "pages"
    label: "Pages"
    label_singular: "Page"
    folder: "src/pages/other-pages"
    create: true
    fields:
      - label: "Template Key"
        name: "templateKey"
        widget: "hidden"
        default: "page"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Description"
        name: "description"
        widget: "text"
        hint: "Please provide a description of what is on this page so that search engines can display what to expect on your page more accurately."
      - label: "Sections"
        name: "sections"
        widget: "list"
        field: {label: "Section", name: "section", widget: "markdown"}
